# 產生上市上櫃台股清單
表格說明：股票代碼/公司名稱/國際證券辨識號碼(ISIN Code)/上市日/市場別/產業別/CFICode

英文對照：stock_id/stock_name/ISIN_Code/Listing_date/Listing_category/Industry_category/CFICode

# 台股號碼一覽表-上市

In [1]:
import pandas as pd
df = pd.read_csv('2.csv', names=['首列','有價證券代號及名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode','備註'])

In [2]:
df.head(3) #看看編碼有沒有錯誤

    首列  有價證券代號及名稱  國際證券辨識號碼(ISIN Code)  上市日  市場別  產業別  CFICode  備註
0  NaN          0                    1    2    3    4        5   6
1  0.0  有價證券代號及名稱  國際證券辨識號碼(ISIN Code)  上市日  市場別  產業別  CFICode  備註
2  1.0         股票                   股票   股票   股票   股票       股票  股票

In [3]:
df.info() #看看資料型態

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22991 entries, 0 to 22990
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   首列                   22990 non-null  float64
 1   有價證券代號及名稱            22991 non-null  object
 2   國際證券辨識號碼(ISIN Code)  22991 non-null  object
 3   上市日                  22991 non-null  object
 4   市場別                  22991 non-null  object
 5   產業別                  977 non-null    object
 6   CFICode              22991 non-null  object
 7   備註                   10 non-null     object
dtypes: float64(1), object(7)
memory usage: 1.4+ MB

In [4]:
mask = df["CFICode"] == "ESVUFR" #篩選出台股
df[mask]

        首列  有價證券代號及名稱 國際證券辨識號碼(ISIN Code)         上市日 市場別    產業別 CFICode   備註
3      2.0    1101　台泥        TW0001101004  1962/02/09  上市   水泥工業  ESVUFR  NaN
4      3.0    1102　亞泥        TW0001102002  1962/06/08  上市   水泥工業  ESVUFR  NaN
5      4.0    1103　嘉泥        TW0001103000  1969/11/14  上市   水泥工業  ESVUFR  NaN
6      5.0    1104　環泥        TW0001104008  1971/02/01  上市   水泥工業  ESVUFR  NaN
7      6.0    1108　幸福        TW0001108009  1990/06/06  上市   水泥工業  ESVUFR  NaN
..     ...        ...                 ...         ...  ..    ...     ...  ...
947  946.0    9944　新麗        TW0009944009  2002/08/26  上市    其他業  ESVUFR  NaN
948  947.0   9945　潤泰新        TW0009945006  1992/04/30  上市    其他業  ESVUFR  NaN
949  948.0  9946　三發地產        TW0009946004  2013/09/17  上市  建材營造業  ESVUFR  NaN
950  949.0    9955　佳龍        TW0009955005  2008/01/21  上市    其他業  ESVUFR  NaN
951  950.0   9958　世紀鋼        TW0009958009  2008/03/12  上市   鋼鐵工業  ESVUFR  NaN

[948 rows x 8 columns]

In [5]:
df2 = df[mask].reset_index(drop=True)
df2[['有價證券代號及名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode']]

     有價證券代號及名稱 國際證券辨識號碼(ISIN Code)         上市日 市場別    產業別 CFICode
0      1101　台泥        TW0001101004  1962/02/09  上市   水泥工業  ESVUFR
1      1102　亞泥        TW0001102002  1962/06/08  上市   水泥工業  ESVUFR
2      1103　嘉泥        TW0001103000  1969/11/14  上市   水泥工業  ESVUFR
3      1104　環泥        TW0001104008  1971/02/01  上市   水泥工業  ESVUFR
4      1108　幸福        TW0001108009  1990/06/06  上市   水泥工業  ESVUFR
..         ...                 ...         ...  ..    ...     ...
943    9944　新麗        TW0009944009  2002/08/26  上市    其他業  ESVUFR
944   9945　潤泰新        TW0009945006  1992/04/30  上市    其他業  ESVUFR
945  9946　三發地產        TW0009946004  2013/09/17  上市  建材營造業  ESVUFR
946    9955　佳龍        TW0009955005  2008/01/21  上市    其他業  ESVUFR
947   9958　世紀鋼        TW0009958009  2008/03/12  上市   鋼鐵工業  ESVUFR

[948 rows x 6 columns]

In [6]:
df2['有價證券代號'] = df2['有價證券代號及名稱'].str.split('\s+').str.get(0)
df2['名稱'] = df2['有價證券代號及名稱'].str.split('\s+').str.get(1)
df2["上市日"] = pd.to_datetime(df2["上市日"], format='%Y/%m/%d')
df3 = df2[['有價證券代號','名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode']]
df3
#這段執行下來有 warning 出現，<ipython-input-212-cf988f8a1199>:2: SettingWithCopyWarning: 
# A value is trying to be set on a copy of a slice from a DataFrame.
# Try using .loc[row_indexer,col_indexer] = value instead
#應該可以再把 code 寫的更好

    有價證券代號    名稱 國際證券辨識號碼(ISIN Code)        上市日 市場別    產業別 CFICode
0     1101    台泥        TW0001101004 1962-02-09  上市   水泥工業  ESVUFR
1     1102    亞泥        TW0001102002 1962-06-08  上市   水泥工業  ESVUFR
2     1103    嘉泥        TW0001103000 1969-11-14  上市   水泥工業  ESVUFR
3     1104    環泥        TW0001104008 1971-02-01  上市   水泥工業  ESVUFR
4     1108    幸福        TW0001108009 1990-06-06  上市   水泥工業  ESVUFR
..     ...   ...                 ...        ...  ..    ...     ...
943   9944    新麗        TW0009944009 2002-08-26  上市    其他業  ESVUFR
944   9945   潤泰新        TW0009945006 1992-04-30  上市    其他業  ESVUFR
945   9946  三發地產        TW0009946004 2013-09-17  上市  建材營造業  ESVUFR
946   9955    佳龍        TW0009955005 2008-01-21  上市    其他業  ESVUFR
947   9958   世紀鋼        TW0009958009 2008-03-12  上市   鋼鐵工業  ESVUFR

[948 rows x 7 columns]

In [7]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   有價證券代號               948 non-null    object
 1   名稱                   948 non-null    object
 2   國際證券辨識號碼(ISIN Code)  948 non-null    object
 3   上市日                  948 non-null    datetime64[ns]
 4   市場別                  948 non-null    object
 5   產業別                  948 non-null    object
 6   CFICode              948 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 52.0+ KB

# 台股號碼一覽表-上櫃

In [8]:
import pandas as pd
df4 = pd.read_csv('4.csv', names=['首列','有價證券代號及名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode','備註'])

In [9]:
df4.head(3) #看看編碼有沒有錯誤

,首列,有價證券代號及名稱,國際證券辨識號碼(ISIN Code),上市日,市場別,產業別,CFICode,備註
0,NaN,0,1,2,3,4,5,6
1,0.0,有價證券代號及名稱,國際證券辨識號碼(ISIN Code),上市日,市場別,產業別,CFICode,備註
2,1.0,上櫃認購(售)權證,上櫃認購(售)權證,上櫃認購(售)權證,上櫃認購(售)權證,上櫃認購(售)權證,上櫃認購(售)權證,上櫃認購(售)權證

In [10]:
df4.info() #看看資料型態

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7100 entries, 0 to 7099
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   首列                   7099 non-null   float64
 1   有價證券代號及名稱            7100 non-null   object
 2   國際證券辨識號碼(ISIN Code)  7100 non-null   object
 3   上市日                  7100 non-null   object
 4   市場別                  7100 non-null   object
 5   產業別                  794 non-null    object
 6   CFICode              7100 non-null   object
 7   備註                   8 non-null      object
dtypes: float64(1), object(7)
memory usage: 443.9+ KB

In [11]:
mask = df4["CFICode"] == "ESVUFR" #篩選出台股
# df4[mask].reset_index(drop=True)

In [12]:
df5 = df4[mask].reset_index(drop=True)
df5[['有價證券代號及名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode']]

      有價證券代號及名稱 國際證券辨識號碼(ISIN Code)         上市日 市場別    產業別 CFICode
0     1240　茂生農經        TW0001240000  2018/08/08  上櫃  農業科技業  ESVUFR
1    1258　其祥-KY        KYG522401010  2011/12/12  上櫃   食品工業  ESVUFR
2       1259　安心        TW0001259000  2011/12/15  上櫃   觀光事業  ESVUFR
3       1264　德麥        TW0001264000  2015/04/09  上櫃   食品工業  ESVUFR
4     1268　漢來美食        TW0001268001  2017/09/27  上櫃   觀光事業  ESVUFR
..          ...                 ...         ...  ..    ...     ...
780     9949　琉園        TW0009949008  2003/11/21  上櫃  文化創意業  ESVUFR
781    9950　萬國通        TW0009950006  2004/02/17  上櫃   塑膠工業  ESVUFR
782     9951　皇田        TW0009951004  2003/12/18  上櫃   電機機械  ESVUFR
783    9960　邁達康        TW0009960005  2004/12/06  上櫃  貿易百貨業  ESVUFR
784     9962　有益        TW0009962001  2006/07/10  上櫃   鋼鐵工業  ESVUFR

[785 rows x 6 columns]

In [13]:
df5['有價證券代號'] = df5['有價證券代號及名稱'].str.split('\s+').str.get(0)
df5['名稱'] = df5['有價證券代號及名稱'].str.split('\s+').str.get(1)
df5["上市日"] = pd.to_datetime(df5["上市日"], format='%Y/%m/%d')
df6 = df5[['有價證券代號','名稱','國際證券辨識號碼(ISIN Code)','上市日','市場別','產業別','CFICode']]
df6
#這段執行下來有 warning 出現，<ipython-input-212-cf988f8a1199>:2: SettingWithCopyWarning: 
# A value is trying to be set on a copy of a slice from a DataFrame.
# Try using .loc[row_indexer,col_indexer] = value instead
#應該可以再把 code 寫的更好

    有價證券代號     名稱 國際證券辨識號碼(ISIN Code)        上市日 市場別    產業別 CFICode
0     1240   茂生農經        TW0001240000 2018-08-08  上櫃  農業科技業  ESVUFR
1     1258  其祥-KY        KYG522401010 2011-12-12  上櫃   食品工業  ESVUFR
2     1259     安心        TW0001259000 2011-12-15  上櫃   觀光事業  ESVUFR
3     1264     德麥        TW0001264000 2015-04-09  上櫃   食品工業  ESVUFR
4     1268   漢來美食        TW0001268001 2017-09-27  上櫃   觀光事業  ESVUFR
..     ...    ...                 ...        ...  ..    ...     ...
780   9949     琉園        TW0009949008 2003-11-21  上櫃  文化創意業  ESVUFR
781   9950    萬國通        TW0009950006 2004-02-17  上櫃   塑膠工業  ESVUFR
782   9951     皇田        TW0009951004 2003-12-18  上櫃   電機機械  ESVUFR
783   9960    邁達康        TW0009960005 2004-12-06  上櫃  貿易百貨業  ESVUFR
784   9962     有益        TW0009962001 2006-07-10  上櫃   鋼鐵工業  ESVUFR

[785 rows x 7 columns]

In [14]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785 entries, 0 to 784
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   有價證券代號               785 non-null    object
 1   名稱                   785 non-null    object
 2   國際證券辨識號碼(ISIN Code)  785 non-null    object
 3   上市日                  785 non-null    datetime64[ns]
 4   市場別                  785 non-null    object
 5   產業別                  785 non-null    object
 6   CFICode              785 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 43.1+ KB

In [15]:
df7 = pd.concat([df3, df6]).reset_index(drop=True)
df7.columns=["stock_id","stock_name",'ISIN_Code','Listing_date','Listing_category','Industry_category','CFICode']
#中文對照：有價證券代號/名稱/國際證券辨識號碼(ISIN Code)/上市日/市場別/產業別/CFICode

In [16]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1733 entries, 0 to 1732
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   stock_id           1733 non-null   object
 1   stock_name         1733 non-null   object
 2   ISIN_Code          1733 non-null   object
 3   Listing_date       1733 non-null   datetime64[ns]
 4   Listing_category   1733 non-null   object
 5   Industry_category  1733 non-null   object
 6   CFICode            1733 non-null   object
dtypes: datetime64[ns](1), object(6)
memory usage: 94.9+ KB

In [17]:
df7.to_csv("stock_list.csv",encoding='utf-8', index=False)

In [18]:
import pandas as pd
check = pd.read_csv('stock_list.csv',sep=',')

In [19]:
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1733 entries, 0 to 1732
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   stock_id           1733 non-null   int64
 1   stock_name         1733 non-null   object
 2   ISIN_Code          1733 non-null   object
 3   Listing_date       1733 non-null   object
 4   Listing_category   1733 non-null   object
 5   Industry_category  1733 non-null   object
 6   CFICode            1733 non-null   object
dtypes: int64(1), object(6)
memory usage: 94.9+ KB

In [20]:
check.head()

,stock_id,stock_name,ISIN_Code,Listing_date,Listing_category,Industry_category,CFICode
0,1101,台泥,TW0001101004,1962-02-09,上市,水泥工業,ESVUFR
1,1102,亞泥,TW0001102002,1962-06-08,上市,水泥工業,ESVUFR
2,1103,嘉泥,TW0001103000,1969-11-14,上市,水泥工業,ESVUFR
3,1104,環泥,TW0001104008,1971-02-01,上市,水泥工業,ESVUFR
4,1108,幸福,TW0001108009,1990-06-06,上市,水泥工業,ESVUFR