# 多股，多月測試 OK

# 可以使用 stock_list.csv 進行單股，2010-2022 的每日交易爬蟲了。

In [1]:
def Stock_crawl(stockNo,Name):
    import pandas as pd
    import numpy as np
    import json
    import requests
    import time
    import random
    from datetime import datetime

    dates=[]
    for i in range (2010,2022):
#     for i in range (2021,2022): #這行供小量測試。

    #     print(i) #確認一下
        for j in range(1,13):
            if j <10:
                j="0"+str(j)
    #         print(str(i)+str(j)) #確認一下
            dates.append(str(i)+str(j)+str("01"))
    #print(dates) #確認一下， dates list 完成。
    starttime=datetime.now() #紀錄多久

    json_list=[]
    json_data=[]
    for Date in dates:
        try:
            url = f'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date={Date}&stockNo={stockNo}'

            data = requests.get(url).text
            json_data = json.loads(data)
            json_list.append(json_data['data'])
            time.sleep (random.randrange(1, 10))
        except:
            print("No data of",Date,Name)
    try:
        json=[] 
        json_stock=[]
        for i in range (0, len(json_list)):
            for j in range(0,len(json_list[i])):
                json_stock.append(json_list[i][j])

        for j in range(0,(len(json_stock))):
            StockPrice = pd.DataFrame(json_stock, columns = ['Date','Volume','Volume_Cash','Open','High','Low','Close','Change','Order'])

            StockPrice['Date'] = StockPrice['Date'].str.replace('/','').astype(int) + 19110000
            StockPrice['Date'] = pd.to_datetime(StockPrice['Date'].astype(str))
            StockPrice['Volume'] = StockPrice['Volume'].str.replace(',','').astype(float)
            StockPrice['Volume_Cash'] = StockPrice['Volume_Cash'].str.replace(',','').astype(float)
            StockPrice['Order'] = StockPrice['Order'].str.replace(',','').astype(float)

            StockPrice['Open'] = StockPrice['Open'].str.replace(',','').astype(float)
            StockPrice['High'] = StockPrice['High'].str.replace(',','').astype(float)
            StockPrice['Low'] = StockPrice['Low'].str.replace(',','').astype(float)
            StockPrice['Close'] = StockPrice['Close'].str.replace(',','').astype(float)
            StockPrice['Change'] = StockPrice['Change'].str.replace(',','').str.replace('+','').str.replace('X','').astype(float)
            StockPrice.insert(0,column='stock_id',value=stockNo)
            StockPrice.insert(1,column='stock_name',value=Name)
            StockPrice = StockPrice[['stock_id','stock_name','Date','Volume','Volume_Cash','Open','High','Low','Close','Change','Order']]
            #中文對照：股票代碼/公司名稱/日期/成交量/成交金額/開盤價/最高價/最低價/收盤價/漲跌幅/交易筆數
    except:
        print("Woops, Something wrong~")

    file_name = "{}_daily.csv".format(stockNo)
    StockPrice.to_csv(file_name, index=False)
    print(file_name+"下載完成...", end="")
    endtime= datetime.now() #紀錄爬取該支股票要多久
    print("執行時間:",endtime-starttime,"秒") #紀錄爬取該支股票要多久
    #1101_daily.csv下載完成...執行時間: 0:12:27.472259 秒
    #1102_daily.csv下載完成...執行時間: 0:12:47.176578 秒

In [2]:
import csv
with open('stock_list.csv') as f:
    list_of_stock = csv.DictReader(f)
    for obj in list_of_stock:
        Stock_crawl(obj['stock_id'],obj['stock_name'])

No data of 20210501 台泥
No data of 20210601 台泥
No data of 20210701 台泥
No data of 20210801 台泥
No data of 20210901 台泥
No data of 20211001 台泥
No data of 20211101 台泥
No data of 20211201 台泥
1101_daily.csv下載完成...執行時間: 0:00:33.726695 秒
No data of 20210501 亞泥
No data of 20210601 亞泥
No data of 20210701 亞泥
No data of 20210801 亞泥
No data of 20210901 亞泥
No data of 20211001 亞泥
No data of 20211101 亞泥
No data of 20211201 亞泥
1102_daily.csv下載完成...執行時間: 0:00:31.815304 秒
No data of 20210501 嘉泥
No data of 20210601 嘉泥
No data of 20210701 嘉泥
No data of 20210801 嘉泥
No data of 20210901 嘉泥
No data of 20211001 嘉泥
No data of 20211101 嘉泥
No data of 20211201 嘉泥
1103_daily.csv下載完成...執行時間: 0:00:31.962201 秒

In [4]:
import pandas as pd
check = pd.read_csv('1101_daily.csv',sep=',')

In [5]:
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stock_id     70 non-null     int64
 1   stock_name   70 non-null     object
 2   Date         70 non-null     object
 3   Volume       70 non-null     float64
 4   Volume_Cash  70 non-null     float64
 5   Open         70 non-null     float64
 6   High         70 non-null     float64
 7   Low          70 non-null     float64
 8   Close        70 non-null     float64
 9   Change       70 non-null     float64
 10  Order        70 non-null     float64
dtypes: float64(8), int64(1), object(2)
memory usage: 6.1+ KB

In [6]:
check.head()

,stock_id,stock_name,Date,Volume,Volume_Cash,Open,High,Low,Close,Change,Order
0,1101,台泥,2021-01-04,13744417.0,594543948.0,43.20,43.50,43.05,43.20,0.00,5884.0
1,1101,台泥,2021-01-05,16631219.0,717454208.0,43.25,43.40,43.00,43.10,-0.10,5512.0
2,1101,台泥,2021-01-06,19007699.0,817300595.0,43.10,43.30,42.80,42.95,-0.15,7543.0
3,1101,台泥,2021-01-07,21050886.0,903047634.0,42.95,43.15,42.85,42.85,-0.10,8180.0
4,1101,台泥,2021-01-08,17406803.0,746290426.0,42.90,43.00,42.80,42.95,0.10,7092.0